### ISSUE TITLE
send message

### ISSUE THREAD

**Issue by rozalski** [JunaidBabu/tdlib-python#1]
Hi! How do I send a message to a user?

**Comment by JunaidBabu** [comment]
it should be something like:
`td_send({'@type': 'sendMessage', 'chat_id_': 'xxxxxxxx', input_message_content_: 'xxxx' })
`


Check the documentation here:
 https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1send_message.html

**Comment by JunaidBabu** [comment]
Try the snippet below (You need to know the chat_id):

```
td_send({'@type': 'sendMessage',
         'chat_id': chat_id,
         'input_message_content': {
             '@type': 'inputMessageText',
             'text': {
                 '@type': 'formattedText',
                 'text': 'test'
             }
         }})
```
