### ISSUE TITLE
Self bot?

### ISSUE THREAD

**Issue by arisawali2014** [JunaidBabu/tdlib-python#2]
Can i use my own telegram account to became a bot?

**Comment by JunaidBabu** [comment]
Yes, execute the login.py to login to your normal account

**Comment by arisawali2014** [comment]
I tried to execute the login.py but it got an error:

python3 login.py                                           Traceback (most recent call last):                                                          File "/data/data/com.termux/files/home/tdlib-python/generic.py", line 12, in <module>       tdjson = CDLL("lib/tdjson32.dll")                                                       File "/data/data/com.termux/files/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen failed: "/data/data/com.termux/files/home/tdlib-python/lib/tdjson32.dll" has bad ELF magic

During handling of the above exception, another exception occurred:                       
Traceback (most recent call last):
  File "login.py", line 3, in <module>                                                        from generic import *
  File "/data/data/com.termux/files/home/tdlib-python/generic.py", line 14, in <module>
    CDLL("lib/zlibd1.dll")                                                                  File "/data/data/com.termux/files/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen failed: "/data/data/com.termux/files/home/tdlib-python/lib/zlibd1.dll" has bad ELF magic
➜  tdlib-python git:(master) ✗

**Comment by JunaidBabu** [comment]
Which operating system is it?

**Comment by arisawali2014** [comment]
I'm using termux on android for running the py

**Comment by JunaidBabu** [comment]
oh, I'm sorry the libs are not compiled for arm. You will have to use an x86 or x86_64 system as of now.
